# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-28 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapinformation',
            name='og_image',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
